GET http://localhost:5247/grades

###
GET http://localhost:5247/grades/13

###
POST http://localhost:5247/grades
Content-Type: application/json

{
    "Name": "Fourteenth"
}

###
PUT http://localhost:5247/grades/13
Content-Type: application/json

{
    "Name": "Thirteenth"
}

###
DELETE http://localhost:5247/grades/50